### ISSUE TITLE
report missing node as missing node if possible via libp2p api

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/fldist#25]
for now it tells version, but I guess libp2p should have key or something

```]
dz@DESKTOP-7O591L6:/mnt/d/git/fluence/fluence-app$ fldist run_air --path describe.clj --node-addr /ip4/34.201.151.205/tcp/31002/ws/p2p/12D3KooWHHENiZjgA9Yh9ANKBhLRSkChPca3juehAwZeXR3qER8B --data '{}'   
object
Something went wrong!
Error: Current version of fldist is incompatible with the connected Fluence node. Please update fldist
    at Function.Distributor.create (/home/dz/.nvm/versions/node/v14.17.0/lib/node_modules/@fluencelabs/fldist/dist/distributor.js:329:19)
    at async Object.argv.getDistributor (/home/dz/.nvm/versions/node/v14.17.0/lib/node_modules/@fluencelabs/fldist/dist/args.js:185:36)
    at async Object.handler (/home/dz/.nvm/versions/node/v14.17.0/lib/node_modules/@fluencelabs/fldist/dist/commands/runAir.js:52:29)
dz@DESKTOP-7O591L6:/mnt/d/git/fluence/fluence-app$
```
At least do not report it as fldist issue

**Comment by folex** [comment]
Plz update to the latest `fldist`, it has been fixed there:
```
$ fldist run_air --path /tmp/air --node-addr /ip4/34.201.151.205/tcp/31002/ws/p2p/12D3KooWHHENiZjgA9Yh9ANKBhLRSkChPca3juehAwZeXR3qER8B --data '{}'
Something went wrong!
Error dialing node /ip4/34.201.151.205/tcp/31002/ws/p2p/12D3KooWHHENiZjgA9Yh9ANKBhLRSkChPca3juehAwZeXR3qER8B:
ERR_ENCRYPTION_FAILED
Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.
```
